import React,{useEffect,useState} from "react";import api from "../services/api";
const defaultFields={name:{visible:true,required:true},class_name:{visible:true,required:true},gender:{visible:true,required:true},admission_no:{visible:true,required:false},pen_number:{visible:true,required:false},father_name:{visible:true,required:false},mother_name:{visible:true,required:false},date_of_birth:{visible:true,required:false},category:{visible:true,required:false},admission_date:{visible:true,required:false}};
const blank=()=>({school_name:"",address:"",udise_code:"",admin_username:"",admin_password:"",classes:[],fields:JSON.parse(JSON.stringify(defaultFields)),dashboard_groups:[]});
export default function Admin(){const role=localStorage.getItem("school_role")||"teacher";const [pw,setPw]=useState({current_password:"",new_password:""}),[teacher,setTeacher]=useState({username:"",password:"",role:"teacher",school_id:null}),[school,setSchool]=useState(blank()),[schools,setSchools]=useState([]),[editing,setEditing]=useState(null),[classText,setClassText]=useState(""),[groupText,setGroupText]=useState(""),[msg,setMsg]=useState("");
const loadSchools=()=>role==="super_admin"&&api.get("/auth/schools").then(r=>setSchools(r.data)).catch(()=>{});
useEffect(()=>{loadSchools()},[]);
const change=async e=>{e.preventDefault();try{const r=await api.post('/auth/change-password',pw);setMsg(r.data.message);setPw({current_password:"",new_password:""})}catch(e){setMsg(e.response?.data?.detail||'Password change failed')}};
const addTeacher=async e=>{e.preventDefault();try{const r=await api.post('/auth/users',teacher);setMsg(r.data.message);setTeacher({username:"",password:"",role:"teacher",school_id:null})}catch(e){setMsg(e.response?.data?.detail||'Could not create account')}};
const payload=()=>({...school,classes:classText.split(',').map(x=>x.trim()).filter(Boolean),dashboard_groups:groupText.split('\n').map(line=>{const [name,list='']=line.split(':');return {name:(name||'').trim(),classes:list.split(',').map(x=>x.trim()).filter(Boolean)}}).filter(g=>g.name)});
const saveSchool=async e=>{e.preventDefault();try{const r=editing?await api.put(`/auth/schools/${editing}`,payload()):await api.post('/auth/schools',payload());setMsg(r.data.message);setSchool(blank());setClassText("");setEditing(null);loadSchools()}catch(e){setMsg(e.response?.data?.detail||'Could not save school')}};
const edit=s=>{setEditing(s.id);setSchool({school_name:s.school_name,address:s.address,udise_code:s.udise_code,admin_username:s.admin_username||"",admin_password:"",classes:s.classes||[],fields: {
  ...JSON.parse(JSON.stringify(defaultFields)),
  ...(s.fields || {})
}});setClassText((s.classes||[]).join(', '));setGroupText((s.dashboard_groups||[]).map(g=>`${g.name}: ${(g.classes||[]).join(', ')}`).join('\n'));window.scrollTo({top:0,behavior:"smooth"})};
const toggle=(k,p,v)=>setSchool({...school,fields:{...school.fields,[k]:{...school.fields[k],[p]:v}}});
return <><header className="page-head"><div><p className="eyebrow">SECURITY & DATA</p><h1>Administration</h1><p className="muted">Role: {role}</p></div></header>{msg&&<div className="alert">{msg}</div>}<section className="panel"><h2>Change Password</h2><form className="form-grid" onSubmit={change}><label>Current password<input type="password" value={pw.current_password} onChange={e=>setPw({...pw,current_password:e.target.value})} required/></label><label>New password<input type="password" minLength="8" value={pw.new_password} onChange={e=>setPw({...pw,new_password:e.target.value})} required/></label><button className="primary-btn">Change Password</button></form></section>
{role==="super_admin"&&<><section className="panel"><h2>{editing?"Edit School & Configuration":"Create New School"}</h2><form onSubmit={saveSchool}><div className="form-grid"><label>School Name<input value={school.school_name} onChange={e=>setSchool({...school,school_name:e.target.value})} required/></label><label>Address<input value={school.address} onChange={e=>setSchool({...school,address:e.target.value})} required/></label><label>UDISE Code<input value={school.udise_code} onChange={e=>setSchool({...school,udise_code:e.target.value})} required/></label><label>School Admin Username<input value={school.admin_username} onChange={e=>setSchool({...school,admin_username:e.target.value})} required/></label><label>{editing?"New Password (leave blank to keep current)":"Admin Password"}<input type="password" minLength={editing?0:8} value={school.admin_password} onChange={e=>setSchool({...school,admin_password:e.target.value})} required={!editing}/></label><label>Classes / Groups (comma separated)<input value={classText} onChange={e=>setClassText(e.target.value)} placeholder="MONT 1, MONT 2, 1, 2, 3"/></label></div><label>Dashboard Groups (one per line: Group Name: class1, class2)<textarea rows="5" value={groupText} onChange={e=>setGroupText(e.target.value)} placeholder={"Pre-Primary: MONT 1, MONT 2, MONT 3\nPrimary: 1, 2, 3, 4, 5\nSecondary: 6, 7, 8, 9, 10"}/></label><h3>Student Record Structure</h3><div className="table-wrap"><table><thead><tr><th>Field</th><th>Visible</th><th>Required</th></tr></thead><tbody>{Object.keys(school.fields).map(k=><tr key={k}><td>{k.replaceAll("_"," ")}</td><td><input type="checkbox" checked={school.fields[k].visible} disabled={["name","class_name","gender"].includes(k)} onChange={e=>toggle(k,"visible",e.target.checked)}/></td><td><input type="checkbox" checked={school.fields[k].required} disabled={["name","class_name","gender"].includes(k)||!school.fields[k].visible} onChange={e=>toggle(k,"required",e.target.checked)}/></td></tr>)}</tbody></table></div><div className="toolbar"><button className="primary-btn">{editing?"Save Changes":"Create School + Admin"}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setSchool(blank());setClassText("")}}>Cancel Edit</button>}</div></form></section>
<section className="panel"><h2>Created Schools and Admins</h2><p className="muted">Passwords are never displayed. Use Edit to set a new password if an admin forgets it.</p><div className="table-wrap"><table><thead><tr><th>School</th><th>UDISE</th><th>School Admin</th><th>Classes / Groups</th><th>Action</th></tr></thead><tbody>{schools.map(s=><tr key={s.id}><td><strong>{s.school_name}</strong><br/><small>{s.address}</small></td><td>{s.udise_code}</td><td>{s.admin_username||"—"}</td><td>{(s.classes||[]).join(", ")||"Not configured"}</td><td><button className="edit-btn" onClick={()=>edit(s)}>Edit</button></td></tr>)}</tbody></table></div></section></>}</>;}
