import React,{useEffect,useMemo,useState} from "react";
import api from "../services/api";
export default function Reports(){
 const [classes,setClasses]=useState([]);useEffect(()=>{api.get("/settings/config").then(r=>setClasses(r.data.classes||[]))},[]); const today=new Date().toISOString().slice(0,10); const [type,setType]=useState("daily"),[date,setDate]=useState(today),[data,setData]=useState(null),[search,setSearch]=useState(""),[className,setClassName]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{let r;if(type==="daily")r=await api.get("/reports/daily",{params:{report_date:date}});if(type==="monthly")r=await api.get("/reports/monthly",{params:{year:+date.slice(0,4),month:+date.slice(5,7)}});if(type==="yearly")r=await api.get("/reports/yearly",{params:{year:+date.slice(0,4)}});setData(r.data)}catch(e){setError(typeof e.response?.data?.detail==="string"?e.response.data.detail:"Could not generate report")}finally{setLoading(false)}};
 const studentRows=useMemo(()=>{const rows=data?.studentwise||[];return rows.filter(r=>(!className||r.class_name===className)&&(!search||r.student_name.toLowerCase().includes(search.toLowerCase())))},[data,search,className]);
 const dailyRows=data?.classwise||[];
 const download=async(path,filename)=>{try{const r=await api.get(path,{responseType:"blob"});const url=URL.createObjectURL(r.data);const a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}catch{setError("Export failed")}};
 const exportButtons=()=>{if(type==="daily")return <div className="toolbar"><button onClick={()=>download(`/exports/daily.xlsx?report_date=${date}`,`daily-${date}.xlsx`)}>Download Excel</button><button onClick={()=>download(`/exports/daily.pdf?report_date=${date}`,`daily-${date}.pdf`)}>Download PDF</button></div>;if(type==="monthly")return <div className="toolbar"><button onClick={()=>download(`/exports/monthly.xlsx?year=${+date.slice(0,4)}&month=${+date.slice(5,7)}`,`monthly-${date.slice(0,7)}.xlsx`)}>Download Excel</button><button onClick={()=>download(`/exports/monthly.pdf?year=${+date.slice(0,4)}&month=${+date.slice(5,7)}`,`monthly-${date.slice(0,7)}.pdf`)}>Download PDF</button></div>;return <div className="toolbar"><button onClick={()=>download(`/exports/yearly.xlsx?year=${+date.slice(0,4)}`,`yearly-${date.slice(0,4)}.xlsx`)}>Download Excel</button><button onClick={()=>download(`/exports/yearly.pdf?year=${+date.slice(0,4)}`,`yearly-${date.slice(0,4)}.pdf`)}>Download PDF</button></div>};
 const totals=data&&type==="daily"?[...(data.groups||[]).map(g=>[g.name,g.summary]),['Grand Total',data.grand_total]]:[];
 return <><header className="page-head"><div><p className="eyebrow">ANALYTICS</p><h1>Attendance Reports</h1><p className="muted">Daily summary and student-wise monthly or yearly attendance.</p></div></header>
 <section className="panel"><div className="report-controls"><label>Report type<select value={type} onChange={e=>{setType(e.target.value);setData(null)}}><option value="daily">Daily Summary</option><option value="monthly">Monthly · Student-wise</option><option value="yearly">Yearly · Student-wise</option></select></label><label>Reference date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="primary-btn" onClick={load} disabled={loading}>{loading?"Generating…":"Generate Report"}</button></div>{error&&<div className="alert error">{error}</div>}</section>
 {data&&type==="daily"&&<div className={data.day_status==="Holiday"?"alert holiday-alert":"alert"}><strong>Day Status: {data.day_status}</strong> · {data.reason}</div>}{data&&<section className="panel"><div className="panel-title-row"><div><h2>Export Report</h2><p className="muted">Excel exports include summary totals and detailed records.</p></div>{exportButtons()}</div></section>}
 {data&&type==="daily"&&<><section className="panel"><h2>Daily Class Summary</h2><div className="table-wrap"><table><thead><tr><th>Class</th><th>Boys Present</th><th>Girls Present</th><th>Total Present</th><th>Total Absent</th><th>Total Marked</th></tr></thead><tbody>{dailyRows.map(r=><tr key={r.class_name}><td><span className="badge">{r.class_name}</span></td><td>{r.boys_present}</td><td>{r.girls_present}</td><td><strong>{r.total_present}</strong></td><td>{r.total_absent}</td><td>{r.total_marked}</td></tr>)}</tbody></table></div></section><section className="panel"><h2>School Group Totals</h2><div className="table-wrap"><table><thead><tr><th>Group</th><th>Boys Present</th><th>Girls Present</th><th>Total Present</th><th>Total Absent</th><th>Total Marked</th><th>Boys Strength</th><th>Girls Strength</th><th>Total Strength</th></tr></thead><tbody>{totals.map(([label,r])=><tr key={label} className={label==='Grand Total'?'grand-row':''}><td><strong>{label}</strong></td><td>{r?.boys_present||0}</td><td>{r?.girls_present||0}</td><td>{r?.total_present||0}</td><td>{r?.total_absent||0}</td><td>{r?.total_marked||0}</td><td>{r?.boys_total||0}</td><td>{r?.girls_total||0}</td><td><strong>{r?.total_students||0}</strong></td></tr>)}</tbody></table></div></section></>}
 {data&&type!=="daily"&&<section className="panel"><div className="panel-title-row"><div><h2>{type==="monthly"?"Monthly":"Yearly"} Student Attendance</h2><p className="muted">Grouped by class and searchable by student name.</p></div><div className="filters"><select value={className} onChange={e=>setClassName(e.target.value)}>{["",...classes].map(c=><option key={c} value={c}>{c?c==="UKG/KG2/PP1"?c:`Class ${c}`:"All Classes"}</option>)}</select><input className="search" placeholder="⌕ Search any student" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="table-wrap"><table><thead><tr><th>Class</th><th>Student Name</th><th>Gender</th><th>Present</th><th>Absent</th><th>Marked Days</th><th>Attendance %</th></tr></thead><tbody>{studentRows.map(r=><tr key={r.student_id}><td><span className="badge">{r.class_name}</span></td><td><strong>{r.student_name}</strong></td><td>{r.gender}</td><td>{r.present}</td><td>{r.absent}</td><td>{r.total_marked_days}</td><td><span className="percent">{r.percentage}%</span></td></tr>)}</tbody></table></div>{studentRows.length===0&&<div className="empty">No matching student attendance found.</div>}</section>}</>;
}
