import React,{ useEffect,useState } from "react";
import api from "../services/api";
export default function TakeAttendance(){
 const [classes,setClasses]=useState([]),[className,setClassName]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[sheet,setSheet]=useState(null),[message,setMessage]=useState("");
 useEffect(()=>{api.get("/attendance/classes").then(r=>{const c=r.data.classes||[];setClasses(c);if(c.length)setClassName(c[0])})},[]);
 const load=async()=>{setMessage("");try{const r=await api.get("/attendance/sheet",{params:{class_name:className,attendance_date:date}});setSheet(r.data)}catch(e){setMessage(e.response?.data?.detail||"Could not load attendance")}};
 const setStatus=(id,status)=>setSheet(s=>({...s,records:s.records.map(x=>x.student_id===id?{...x,status}:x)}));
 const markAll=status=>setSheet(s=>({...s,records:s.records.map(x=>({...x,status}))}));
 const save=async()=>{const payload={class_name:className,attendance_date:date,records:sheet.records.map(({student_id,status})=>({student_id,status}))};try{const r=sheet.submitted?await api.put("/attendance/edit",payload):await api.post("/attendance/submit",payload);setMessage(`${r.data.message}. Edits remaining: ${r.data.edits_remaining}`);await load()}catch(e){setMessage(e.response?.data?.detail||"Could not save attendance")}};
 return <><header className="page-head"><div><p className="eyebrow">DAILY REGISTER</p><h1>Take Attendance</h1><p className="muted">Mark present or absent. A submitted class sheet can be edited up to 6 times.</p></div></header><section className="panel"><div className="report-controls"><label>Class<select value={className} onChange={e=>{setClassName(e.target.value);setSheet(null)}}>{classes.map(c=><option key={c} value={c}>{c==="UKG/KG2/PP1"?c:`Class ${c}`}</option>)}</select></label><label>Date<input type="date" value={date} onChange={e=>{setDate(e.target.value);setSheet(null)}}/></label><button className="primary-btn" onClick={load}>Load Students</button></div>{message&&<div className="alert">{message}</div>}</section>
 {sheet&&<section className="panel"><div className="panel-title-row"><div><h2>{className==="UKG/KG2/PP1"?className:`Class ${className}`} Register</h2><p className="muted">{sheet.submitted?`${sheet.edits_remaining} of 6 edits remaining`:"New attendance sheet"}{sheet.is_locked&&" · LOCKED"}</p></div><div className="quick-actions"><button onClick={()=>markAll("Present")} disabled={sheet.is_locked}>Mark all Present</button><button onClick={()=>markAll("Absent")} disabled={sheet.is_locked}>Mark all Absent</button></div></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Student Name</th><th>Gender</th><th>Attendance</th></tr></thead><tbody>{sheet.records.map((s,i)=><tr key={s.student_id}><td>{i+1}</td><td><strong>{s.name}</strong></td><td>{s.gender}</td><td><div className="status-toggle"><button className={s.status==="Present"?"present selected":"present"} onClick={()=>setStatus(s.student_id,"Present")} disabled={sheet.is_locked}>Present</button><button className={s.status==="Absent"?"absent selected":"absent"} onClick={()=>setStatus(s.student_id,"Absent")} disabled={sheet.is_locked}>Absent</button></div></td></tr>)}</tbody></table></div><div className="save-bar"><span>{sheet.records.length} students</span><button className="primary-btn" onClick={save} disabled={sheet.is_locked||!sheet.records.length}>{sheet.submitted?"Save Attendance Edit":"Submit Attendance"}</button></div></section>}</>;
}
