from datetime import datetime
from sqlalchemy import Column,Integer,String,Date,DateTime,Boolean,ForeignKey,UniqueConstraint,Text
from sqlalchemy.orm import relationship
from .database import Base
class School(Base):
 __tablename__='schools'; id=Column(Integer,primary_key=True); school_name=Column(String,nullable=False); address=Column(String,nullable=False); udise_code=Column(String,unique=True,nullable=False); is_active=Column(Boolean,default=True,nullable=False); created_at=Column(DateTime,default=datetime.utcnow)
class User(Base):
 __tablename__='users'; id=Column(Integer,primary_key=True); username=Column(String,unique=True,nullable=False); password_hash=Column(String,nullable=False); role=Column(String,default='teacher',nullable=False); school_id=Column(Integer,ForeignKey('schools.id'),nullable=True,index=True); must_change_password=Column(Boolean,default=False); school=relationship('School')
class AcademicYear(Base):
 __tablename__='academic_years'; id=Column(Integer,primary_key=True); school_id=Column(Integer,ForeignKey('schools.id'),nullable=False,index=True); name=Column(String,nullable=False); start_date=Column(Date,nullable=False); end_date=Column(Date,nullable=False); is_active=Column(Boolean,default=False); __table_args__=(UniqueConstraint('school_id','name',name='uq_school_academic_year'),)
class Student(Base):
 __tablename__='students'; id=Column(Integer,primary_key=True,index=True); school_id=Column(Integer,ForeignKey('schools.id'),nullable=False,index=True); name=Column(String,nullable=False); class_name=Column(String,nullable=False,index=True); section=Column(String,nullable=True); stream=Column(String,nullable=True); gender=Column(String,nullable=False); admission_no=Column(String,nullable=True); pen_number=Column(String,nullable=True); father_name=Column(String,nullable=True); mother_name=Column(String,nullable=True); date_of_birth=Column(Date,nullable=True); category=Column(String,nullable=True); admission_date=Column(Date,nullable=True); is_active=Column(Boolean,default=True); exit_status=Column(String,nullable=True); exit_date=Column(Date,nullable=True); exit_reason=Column(String,nullable=True); created_at=Column(DateTime,default=datetime.utcnow); attendances=relationship('Attendance',back_populates='student'); school=relationship('School'); __table_args__=(UniqueConstraint('school_id','admission_no',name='uq_student_school_admission'),UniqueConstraint('school_id','pen_number',name='uq_student_school_pen'))
class StudentEnrollment(Base):
 __tablename__='student_enrollments'; id=Column(Integer,primary_key=True); student_id=Column(Integer,ForeignKey('students.id'),nullable=False,index=True); academic_year_id=Column(Integer,ForeignKey('academic_years.id'),nullable=False,index=True); class_name=Column(String,nullable=False); section=Column(String,nullable=True); stream=Column(String,nullable=True); status=Column(String,default='Active'); __table_args__=(UniqueConstraint('student_id','academic_year_id',name='uq_student_year'),)
class TeacherAssignment(Base):
 __tablename__='teacher_assignments'; id=Column(Integer,primary_key=True); user_id=Column(Integer,ForeignKey('users.id'),nullable=False,index=True); school_id=Column(Integer,ForeignKey('schools.id'),nullable=False,index=True); academic_year_id=Column(Integer,ForeignKey('academic_years.id'),nullable=True); class_name=Column(String,nullable=False); section=Column(String,nullable=True); __table_args__=(UniqueConstraint('user_id','academic_year_id','class_name','section',name='uq_teacher_assignment'),)
class AttendanceSession(Base):
 __tablename__='attendance_sessions'; id=Column(Integer,primary_key=True); school_id=Column(Integer,ForeignKey('schools.id'),nullable=False,index=True); academic_year_id=Column(Integer,ForeignKey('academic_years.id'),nullable=True,index=True); class_name=Column(String,nullable=False); section=Column(String,nullable=True); attendance_date=Column(Date,nullable=False); edit_count=Column(Integer,default=0); is_locked=Column(Boolean,default=False); created_by=Column(Integer,ForeignKey('users.id'),nullable=True); created_at=Column(DateTime,default=datetime.utcnow); updated_at=Column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow); __table_args__=(UniqueConstraint('school_id','class_name','section','attendance_date',name='uq_school_class_section_date_session'),)
class Attendance(Base):
 __tablename__='attendance'; id=Column(Integer,primary_key=True); student_id=Column(Integer,ForeignKey('students.id'),nullable=False); academic_year_id=Column(Integer,ForeignKey('academic_years.id'),nullable=True,index=True); attendance_date=Column(Date,nullable=False,index=True); status=Column(String,nullable=False); created_at=Column(DateTime,default=datetime.utcnow); updated_at=Column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow); student=relationship('Student',back_populates='attendances'); __table_args__=(UniqueConstraint('student_id','attendance_date',name='uq_student_date'),)
class AttendanceHistory(Base):
 __tablename__='attendance_history'; id=Column(Integer,primary_key=True); attendance_id=Column(Integer,ForeignKey('attendance.id'),nullable=False); student_id=Column(Integer,ForeignKey('students.id'),nullable=False); attendance_date=Column(Date,nullable=False); old_status=Column(String,nullable=False); new_status=Column(String,nullable=False); edited_by=Column(Integer,ForeignKey('users.id'),nullable=True); edited_at=Column(DateTime,default=datetime.utcnow)
class SchoolCalendar(Base):
 __tablename__='school_calendar'; id=Column(Integer,primary_key=True); school_id=Column(Integer,ForeignKey('schools.id'),nullable=False,index=True); academic_year_id=Column(Integer,ForeignKey('academic_years.id'),nullable=True); calendar_date=Column(Date,nullable=False); day_type=Column(String,default='Working Day'); description=Column(String,nullable=True); __table_args__=(UniqueConstraint('school_id','calendar_date',name='uq_school_calendar_date'),)
class AuditLog(Base):
 __tablename__='audit_logs'; id=Column(Integer,primary_key=True); school_id=Column(Integer,ForeignKey('schools.id'),nullable=True,index=True); user_id=Column(Integer,ForeignKey('users.id'),nullable=True); action=Column(String,nullable=False); entity_type=Column(String,nullable=False); entity_id=Column(String,nullable=True); old_value=Column(Text,nullable=True); new_value=Column(Text,nullable=True); created_at=Column(DateTime,default=datetime.utcnow,index=True)
class SchoolSetting(Base):
 __tablename__='school_settings'; id=Column(Integer,primary_key=True); school_name=Column(String,nullable=False); address=Column(String,nullable=False); udise_code=Column(String,nullable=False)
class SchoolConfig(Base):
 __tablename__='school_configs'; id=Column(Integer,primary_key=True); school_id=Column(Integer,ForeignKey('schools.id'),unique=True,nullable=False,index=True); classes_json=Column(Text,nullable=False,default='[]'); fields_json=Column(Text,nullable=False,default='{}'); dashboard_groups_json=Column(Text,nullable=False,default='[]'); school=relationship('School')
